### PR TITLE
Code Review Request

### PR DESCRIPTION
**Pull request by johnsonsirv**
The **Game Controller** is responsible for the overall game logic which involves player interactions with game board & UI. It determines the Player turn, Win or Draw, and Gameover status.

The interactions with the CLI is encapsulated to the **UserInterface**. 
The **Player** plays his turn (makes move) and the **Board** status is updated accordingly

Kindly review code to merge into master

### CODE REVIEW

**Review by adriaanbd — CHANGES_REQUESTED** [review]
# First Review

Good job stitching this one together. This is not an easy project.

## Requirements
- [x] Descriptive Readme
- [ ] Project met collaborative / solo requirement
- [x] The board is displayed between turns
- [ ] The game can determine a winner
- [x] The app can determine a draw
- [ ] User interaction commands should be in one executable file main.rb
- [x] Game logic is in a class
- [x] Project uses at least two classes
- [x] Project respects DRY rule
- [ ] No hardcoded values
- [x] The board stores a character that represents the empty state (*you did this via and Integer, a clear distinction with string*)
- [x] A Player class with player attributes and a Game class with player instances.

### Project met collaborative / solo requirement

This project was supposed to be done in a collaborative environment. Please refer to [this article](https://microverse-students.crisp.help/en-us/article/i-did-a-collaborative-project-solo-what-happens-now-bh5b1q/?1559072200212) on the matter. Please take note of that.

### The game determines a winner

Nice trick with the `Array.combination(3)` and Set intersection on Winning Combinations, but when I ran the script, the game failed to determine the winner on both occasions, for either X or O. Your `win?` and `game_over?` method look alright, but somehow your `until game_over?` loop in your your `Game#start` does not break when a winning combination on both players or a draw is found.

### User interaction commands

I noticed you have a `game_cli.rb` & `game.rb` file. The UI related stuff is kept for the first and game logic in the second. Good approach. Following this line of thought: does `is_valid_move?(move)` really belong here? 

In addition to the above, there's a `play` method in your `Player` class, and the action to play is really game logic, is it not?

### No Hard Coded values

I liked how you guaranteed immutability of your winning combinations array with `WINNING_COMBINATIONS.freeze`. Another approach to avoid hard coding winning combinations would be to iterate through rows and/or columns returning a boolean on whether the character found are all the same, e.g. all X's or all O's (not nil of course). 

## Other considerations

### Game.`draw?`



Your method is returning a boolean either way. No need to explicitly declare it, unless you have a reason to?

This:

```
  def draw?
    return true if @board.full?
    false
  end
```

Can be:

```
def draw?
    @board.full?
end
```

### Game.`valid_position(position, player)`

This function is a good case for recursion.

This:

```
  def valid_position(position, player)
    unless @board.position_is_free?(position)
      loop do
        show_board_occupied_warning(player.name)
        position = player.play(player.symbol)
        valid_position(position, player)
        return position if @board.position_is_free?(position)
      end
    end

    position
  end
```

Can be:

```
def valid_position(position, player)
    unless @board.position_is_free?(position)
        show_board_occupied_warning(player.name)
        position = player.play(player.symbol)
        valid_position(position, player)
    end

    position
  end
```

### attr_accessor

I noticed you've only used attr_accessor in all your classes . Just beware that this allows other classes to change your instance variables, whereas attr_readers and attr_writers are to be used for instance variables meant for reading only and/or writing only. The accessor is for both read and write.

### DRY

I know I marked you done on this point, because you've done a good job, but there is still some repetition like checking for valid position in your `Game` class and inside your `game_cli` as well.  


The OOP design for this project could be a little better if classes are organized with clear attributes and responsibilities.

### OOP Design

Your `Game` class seems to be doing a lot of stuff, whereas your `Board` to little. Is it really `Game`'s responsibility to determine winner or draw, game over, switch players, call `game_cli` methods to show board, game over statuses and all of that? I think there could be better class organization if you put some thought into your class responsibilities and respect their boundaries.

Great job overall, hoping to be able to play your game correctly next time!

Feel free to reach me via Slack if you have further questions / doubts.

**Comment by johnsonsirv** [comment]
Thank you @adriaanbd for this excellent review.

**Comment by johnsonsirv** [comment]
Changes requested completed. Submitting for another review

**Comment by johnsonsirv** [comment]
Done

**Pull request closed without merging**
